In [2]:
import numpy as np

# Python lists
ls = [[1, 2], [3, 4]]
print(ls)
ls[0][1]

# Poor performance (relative to what?), also mixed types are allowed


[[1, 2], [3, 4]]


2

Numpy implements these things behind the scenes in c which give better performance

In [6]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

#type safety, this doesn't work:
array[0][1] = 'hello'

[[1 2]
 [3 4]]
[[5 2]
 [3 4]]


In [7]:
#By default its an int array:
arr[0][0] = 5.6
print(arr)

[[5 2]
 [3 4]]


Some performance comparison

In [ ]:
ls = list(range(100000))
arr = np.arange(100000)

In [11]:
%%timeit
s = 0
for i in range(100000):
  s += i * i

s

100 loops, best of 3: 8.72 ms per loop


In [13]:
# Super fast!
%%timeit
s2 = 0
s2 += np.sum(arr*arr)
s2

1000 loops, best of 3: 222 µs per loop


# Pandas and Seaborn
 
## Pandas 
for example - group by
**Works in memory**, fast, but limited for large sizes
Can read from many sources, like clipboard, csv, json, sql source (query with some connection), parquet and many more.

Doesn't fit large data sets (in memory)

## Seaborn
view the data in a graphical way

In [17]:
import pandas as pd
import seaborn as sb

# Upload any csv to Files
dataframe = pd.read_csv("./pandas/addresses.csv") # Table
# Info including size in memory
dataframe.info()
dataframe


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   John               4 non-null      object
 1   Doe                5 non-null      object
 2   120 jefferson st.  4 non-null      object
 3   Riverside          5 non-null      object
 4    NJ                5 non-null      object
 5    08075             5 non-null      int64 
dtypes: int64(1), object(5)
memory usage: 368.0+ bytes


John       Doe  ...   NJ  08075
0                   Jack  McGinnis  ...   PA   9119
1          John "Da Man"    Repici  ...   NJ   8075
2                Stephen     Tyler  ...   SD  91234
3                    NaN  Blankman  ...   SD    298
4  Joan "the bone", Anne       Jet  ...   CO    123

[5 rows x 6 columns]

In [21]:
dataframe = pd.read_csv('https://raw.githubusercontent.com/goodby/csv/master/example/user.csv')
dataframe

1  alice alice@example.com
0  2    bob   bob@example.com
1  3  carol  carol@eample.com

In [22]:
dataframe = pd.read_csv("./pandas/addresses.csv") # Table
dataframe.head() # first few records
dataframe.info() # Field types, number of record of each field, null count (missing data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   John               4 non-null      object
 1   Doe                5 non-null      object
 2   120 jefferson st.  4 non-null      object
 3   Riverside          5 non-null      object
 4    NJ                5 non-null      object
 5    08075             5 non-null      int64 
dtypes: int64(1), object(5)
memory usage: 368.0+ bytes


Using info, we can learn how many records are missing in the dataset
You get the record count, column count, number of non-null count.
data typs (object is string)

Good for data preperation


In [23]:
# Get stats info for the table with one call, avg, min, max, std div, etc.
dataframe.describe()

08075
count      5.000000
mean   21769.800000
std    39059.209909
min      123.000000
25%      298.000000
50%     8075.000000
75%     9119.000000
max    91234.000000

When completing missing data, it might be useful to fill missing data with avg. but only if the std div is small.

In [26]:
arr1 = np.array([100, 100, 0, 0])
arr2 = np.array([48, 48, 52, 52])
print(arr1.mean())
print(arr1.std()) 

print(arr2.mean())
print(arr2.std())


50.0
50.0
50.0
2.0


It's important to find values that doesn't make sense, for example with max, min etc. and to eliminate them if they are errors, or if they simply doesn't make sense with the general data, so called "outliers".
for example in a list of apartment prices, we have one or two multi million apts, which doesn't coinside with the rest of the data.

You can then query the data for these outliers:

In [ ]:
dataframe.query("income > 40000") # Example from different data

In [ ]:
# And also, you can describe by column and property (e.g. max)
dataframe.describe().Age.max() # Example from different data
# Some examples
dataframe.Country.unique()
# group my country
dataframe.groupby(['Country']).mean()
# group my country AND gender
dataframe.groupby(['Country', 'gen']).mean()


Pandas cheat sheet:
https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf